const arrLang = {
	'en': {
		'max-score': 'Max-score:',
		'modal-title-gameover': 'Game over',
		'your-score': 'Your score:',
		'restart': 'Restart',
		'main-menu': 'Main menu',
		'title': 'Snake-game',
		'start': 'Start',
		'settings': 'Settings',
		'settings-title': 'Settings',
		'language': 'Language',
		'game-size': 'Game-place size',
		'small': 'Small',
		'medium': 'Medium',
		'large': 'Large',
		'snake-speed': 'Snake speed',
		'slow': 'Slow',
		'regular': 'Regular',
		'fast': 'Fast',
		'pause-game': 'Game paused',
		'continue': 'Continue',
		'volume': 'Volume',
		'about': 'About',
		'game-mode': 'Select game-mode',
		'classic': 'Classic:',
		'classic-btn': 'Classic',
		'timelimited': 'Time-mode:',
		'timelimited-btn': 'Time-mode',
		'btn-gamemode': 'Game-mode',
		'modal-title-win': 'You win!',
		'sec': 'Time:',
		'about-text': 'The project was developed by Junior Front-end by developer Dmytro Soroka in two days... If you have questions or recommendations about the game - contact my social networks',
		'score': 'Score:'
	},
	'ua': {
		'max-score': 'Рекорд:',
		'modal-title-gameover': 'Ви програли',
		'your-score': 'Твій результат:',
		'restart': 'Почати знову',
		'main-menu': 'Головне меню',
		'title': 'Змійка',
		'start': 'Почати',
		'settings': 'Налаштування',
		'settings-title': 'Налаштування',
		'language': 'Мова',
		'game-size': 'Розмір полотна',
		'small': 'Мале',
		'medium': 'Середнє',
		'large': 'Велике',
		'snake-speed': 'Швідкість',
		'slow': 'Повільна',
		'regular': 'Середня',
		'fast': 'Швидка',
		'pause-game': 'Гра зупинена',
		'continue': 'Продовжити',
		'volume': 'Гучність',
		'about': 'Про нас',
		'game-mode': 'Оберіть режим гри',
		'classic': 'Звичайний:',
		'classic-btn': 'Звичайний',
		'timelimited': 'На час:',
		'timelimited-btn': 'На час',
		'btn-gamemode': 'Режим гри',
		'modal-title-win': 'Ти виграв!',
		'sec': 'Час:',
		'about-text': 'Проєкт розроблений Junior Front-end розробником Дмитром Сорокою за два дні... Якщо є питання чи рекомендації по грі – звертайтесь у мої соціальні мережі',
		'score': 'Очки:',
	},
};

export default arrLang;